library(tidyverse)
library(irr)


### 1.1
zilo_classes <- read_csv("C:\\Users\\Äîêóìåíòû\\Çàäàíèå R\\hw1_1_zilo_class.csv")
zilo_classes


### 1.2
zilo_classes %>% 
     select(s_id, stimulus, translation_ru, stimulus_source, class) %>% 
     spread(key = s_id, value = class) ->
     zilo_classes_short
zilo_classes_short
print(agree(zilo_classes_short[,-c(1:3)]))


### 1.3
zilo_classes_2s <- zilo_classes_short[,c(7, 11)]
print(agree(zilo_classes_2s))
print(table(zilo_classes_2s))
p_o <- (44+36)/(44+36+4+5)
p_e <- ((44+5)*(44+4)+(36+5)*(36+4))/(44+36+4+5)^2
coehns_kappa <- (p_o - p_e)/(1 - p_e)
kappa2(zilo_classes_2s)


### 1.4
zilo_classes %>% 
  count(w_id, class) %>% 
  spread(key = class, value = n, fill = 0) %>% 
  mutate(P_i = (choose(b, 2) + choose(r, 2))/ choose(16, 2))
  
zilo_classes %>% 
  count(w_id, class) %>% 
  spread(key = class, value = n, fill = 0) %>% 
  mutate(P_i = (choose(b, 2) + choose(r, 2))/ choose(16, 2)) %>% 
  summarise(P_o = mean(P_i)) %>% 
  unlist ->
  P_o
P_o
  
zilo_classes %>% 
  group_by(class) %>% 
  summarise(n = n()) %>% 
  mutate(freq = n / sum(n))
  
zilo_classes %>% 
  group_by(class) %>% 
  summarise(n = n()) %>% 
  mutate(freq_2 = (n / sum(n))^2) %>% 
  summarise(P_e = sum(freq_2)) %>% 
  unlist ->
  P_e
P_e

Fleiss_kappa <- (P_o-P_e)/(1-P_e)
Fleiss_kappa <- unname(Fleiss_kappa)
Fleiss_kappa

kappam.fleiss(zilo_classes_short[,-c(1:3)])


### 1.5
"Áîëüøèíñòâî îöåíùèêîâ èäåíòè÷íû â ñâîèõ ñóæäåíèÿõ. 7 è 11 îöåíùèêè ñóùåñòâåííî ñîãëàñíû. Ñòåïåíü ñîãëàñèÿ ó îöåíùèêîâ òàêæå äîñòàòî÷íî âûñîêàÿ - 0.85"


### 2.1
df_verbs <- read_csv("C:\\Users\\Äîêóìåíòû\\Çàäàíèå R\\\hw1_2_verbs.csv")
count(unique(df_verbs['SubjectCode']))


### 2.2
df_verbs %>% 
      group_by(WordType,Gender)%>%
      summarise(mean = mean(GivenScore))
      

### 2.3
df_verbs %>% 
      select(SubjectCode, Stimulus, WordType, GivenScore) %>% 
      spread(key = SubjectCode, value = GivenScore) ->
      df_verbs_short


df_verbs_short <- df_verbs_short[complete.cases(df_verbs_short), ]
df_verbs_short
agree(df_verbs_short[,-c(1:2)])


### 2.4
kappam.fleiss(df_verbs_short[,-c(1:2)])


### 2.5
icc(df_verbs_short[,-c(1:2)], model = "twoway", type = "agreement")


### 2.6
kendall_table = data.frame(cor(df_verbs_short[,-c(1:2)], method = "kendall"))
kendall_table
      
